### PR TITLE
Allow passing non-default provider

### PR DESCRIPTION
**Pull request by OJFord**

### CODE REVIEW

**Review by johntdyer — COMMENTED** [review]
(wrong thread)

**Comment by SteveChurch** [comment]
@johntdyer do you think we could request a merge of this PR, please? - We're currently relying on a fork with these changes and would prefer to rely on the base repository.

**Review by johntdyer — APPROVED** [review]

**Comment by SteveChurch** [comment]
@johntdyer Thanks for approving.

**Comment by SteveChurch** [comment]
@builtinnya Nudge ;-)

**Comment by builtinnya** [comment]
Thanks guys! LGTM

**Comment by builtinnya** [comment]
Sorry, I had to revert 04e719d because Terraform 0.12 doesn't support the syntax (ref: https://developer.hashicorp.com/terraform/language/providers/requirements#v0-12-compatible-provider-requirements).
It may be better to add a separate directory like `module-v1` to support modern versions of Terraform.

**Comment by OJFord** [comment]
@builtinnya Do you want to/intend to maintain three different versions though?

An alternative would be to version this module itself; on merging this then the latest (major) version would only support tf v1, users still using older terraform ~should upgrade!~ would need to use an older version.

If the older versions are just intended to stay as they are and not be updated, then there's no need for separate directories or to actually 'keep' them (in the current tree) - the module source can be specified as a specific tag/branch/sha even without versioning.

**Pull request merged**
