### PR TITLE
Support to set default emoji

### PR DESCRIPTION
**Pull request by umisora**
# About 

I want to change the emoji because default emoji is not cool.

# Change to

Changed lambda to accept env of default_emoji.

# How to use
Specify default_emoji in your terraform code 
```
module "sns_to_slack" {
  source = "github.com/xxxxxxx/aws-sns-slack-terraform/module"

  slack_webhook_url = "hooks.slack.com/services/xxxxxxxx/xxxxxxxx"
  slack_channel_map = "{ \"topic-name\": \"#slack-channel\" }"
  default_emoji     = ":tada:"  ← New
}
```

### CODE REVIEW

**Comment by umisora** [comment]
Sample Slack UI ( in my project )

image

**Comment by umisora** [comment]
@builtinnya 
Thank you for your aws-sns-slack-terraform.
Please review this PR.

**Review by builtinnya — APPROVED** [review]
Thank you for your PR!
LGTM :+1:

**Comment by umisora** [comment]
Thank you for your review!

**Pull request merged**
